# Generated by Django 5.2.17 on 2026-09-24 04:04

import transcritor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('video_file', models.FileField(max_length=255, upload_to=transcritor.models.video_upload_to)),
                ('audio_file', models.FileField(blank=True, max_length=255, upload_to='')),
                ('thumbnail', models.FileField(blank=True, max_length=255, upload_to='')),
                ('transcription', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando processamento'), ('EXTRACTING_AUDIO', 'Extraindo áudio'), ('TRANSCRIBING', 'Transcrevendo'), ('COMPLETED', 'Transcrição concluída'), ('ERROR', 'Erro no processamento')], db_index=True, default='PENDING', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vídeo',
                'verbose_name_plural': 'vídeos',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
