# Generated by Django 5.2 on 2026-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcritor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_audio',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
